import Head from "next/head";
import { getAllPosts } from "../lib/notionAPI";
import SinglePosts from "../components/Posts/SinglePosts";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  return {
    props: {
      allPosts: allPosts,
    },
  }
}

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Hello World</h1>
        {allPosts.map((allPost, index) => (
          <div className="mx-4" key={index}>
            <SinglePosts
              title={allPost.title}
              date={allPost.date}
              description={allPost.description}
              tag={allPost.tag}
              slug={allPost.slug}
            />
            {/* {allPost.title} */}
          </div>
        ))}
      </div>
    </>
  );
}
